### PR TITLE
Support Rails 7

### PR DESCRIPTION
**Pull request by Maimer**

### CODE REVIEW

**Comment by mqchau** [comment]
@rmacklin Please review when you can

**Comment by rmacklin** [comment]
Thanks for the PR! I didn't realize AppFolio was still using this gem after all these years. It'd be nice to add a Rails 7 test application, like we did when adding support for Rails 6 in https://github.com/rmacklin/sprockets-bumble_d/pull/14. Short of that, could you at least confirm if you've verified that the gem works in a Rails 7 application before I merge this?

**Comment by mqchau** [comment]
Well, we are struggling to get tests to pass for Rails 6.1 . We're looking into not using this gem anymore.

**Comment by rmacklin** [comment]
Are you referring to tests in your application, or tests in this repository? I fixed the tests in this repository in 13099d85b04aa33ba0bdab27c8c0729c20e5b063

**Comment by Maimer** [comment]
> Thanks for the PR! I didn't realize AppFolio was still using this gem after all these years. It'd be nice to add a Rails 7 test application, like we did when adding support for Rails 6 in #14. Short of that, could you at least confirm if you've verified that the gem works in a Rails 7 application before I merge this?

We are still using the gem, but as @mqchau said we are hoping to remove it soon. Thanks for fixing the tests in the repository. I can try to add a Rails 7 test application, but will need to familiarize myself with how that was done in the PR you linked. I haven't tested that this works with a Rails 7 application yet, so I can understand if you want to wait for that test app.

**Comment by mqchau** [comment]
oh wow thanks for fixing the tests. The unexpected UMD outputs are the errors that I got into.

**Pull request closed without merging**
